// Sample roadmap items with both projects and courses
export const sampleRoadmapItems = {
  id: "1",
  title: "Frontend Development Roadmap",
  items: [
    {
      id: "html-basics",
      title: "HTML Fundamentals",
      description: "Learn the foundation of web development",
      icon: "🌐",
      difficulty: "Beginner",
      duration: "2-3 weeks",
      color: "#10b981",
      type: "course",
    },
    {
      id: "css-styling",
      title: "CSS Styling & Layout",
      description: "Master modern CSS and responsive design",
      icon: "🎨",
      difficulty: "Intermediate",
      duration: "3-4 weeks",
      color: "#f59e0b",
      type: "course",
    },
    {
      id: "portfolio-website",
      title: "Build Portfolio Website",
      description: "Create a personal portfolio using HTML and CSS",
      icon: "💼",
      difficulty: "Beginner",
      duration: "1-2 weeks",
      color: "#f59e0b",
      type: "project",
    },
    {
      id: "responsive-landing",
      title: "Responsive Landing Page",
      description: "Design and build a mobile-first landing page",
      icon: "📱",
      difficulty: "Intermediate",
      duration: "2-3 weeks",
      color: "#8b5cf6",
      type: "project",
    },
    {
      id: "javascript-basics",
      title: "JavaScript Programming",
      description: "Build interactive web applications",
      icon: "⚡",
      difficulty: "Intermediate",
      duration: "4-6 weeks",
      color: "#f59e0b",
      type: "course",
    },
    {
      id: "todo-app",
      title: "Todo Application",
      description: "Create a functional todo app with JavaScript",
      icon: "✅",
      difficulty: "Intermediate",
      duration: "2-3 weeks",
      color: "#ef4444",
      type: "project",
    },
    {
      id: "react-fundamentals",
      title: "React Development",
      description: "Create modern user interfaces",
      icon: "⚛️",
      difficulty: "Advanced",
      duration: "5-7 weeks",
      color: "#8b5cf6",
      type: "course",
    },
    {
      id: "ecommerce-app",
      title: "E-commerce Dashboard",
      description: "Build a full-stack e-commerce application",
      icon: "🛒",
      difficulty: "Advanced",
      duration: "4-6 weeks",
      color: "#8b5cf6",
      type: "project",
    },
  ],
};
